---
elasticsearch:
  build: elas
  container_name: elasticsearch
  net: elk

logstash:
  image: logstash
  ports:
    - 514:514
  container_name: logstash
  net: elk
  command: "logstash -e 'input { syslog { type => syslog port => 5514 } } output { stdout { } elasticsearch { hosts => [ \"elasticsearch\" ] } } filter { json { source => \"message\" } }'"

kibana:
  image: kibana:4.3
  container_name: kibana
  ports:
    - 5601:5601
  net: elk
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
