---
# Data only container
search-data:
  image: elasticsearch
  volumes:
    - /usr/share/elasticsearch/data
  entrypoint: /bin/echo search-data Data only container for elasticsearch

elasticsearch:
  build: elas
  container_name: elasticsearch
  command: ["elasticsearch", "-Des.network.host=0.0.0.0"]
  volumes_from:
    - search-data

logstash:
  image: logstash
  ports:
    - 5514:5514
  container_name: logstash
  command: "logstash -e 'input { syslog { type => syslog port => 5514 } } output { stdout { } elasticsearch { hosts => [ \"elasticsearch\" ] } } filter { json { source => \"message\" } }'"

kibana:
  image: kibana
  container_name: kibana
  ports:
    - 5601:5601
# Shouldn't have had to provide this env variable. Something seems off with the image
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
